[package]
name = "tiny_png"
license = "LGPL-2.1"
# homepage = ""
# documentation = ""
repository = "https://github.com/js29a/tiny_png"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "minimalist truecolor PNG writer and loader"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
futures = "0.3.28"
flate2 = "1.0"
crc32fast = "1.2.0"
quicklz = "0.3.1"
futures-executor = "0.3.28"
